version: "3.9"

services:
  app:
    build: .
    container_name: service-desk-app
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: service_desk_db
    environment:
      POSTGRES_DB: service_desk_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty007
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./01_dump.sql:/docker-entrypoint-initdb.d/init.sql

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  db_data:
  caddy_data:
  caddy_config:
